time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
time python3 gradescope.py
